services:
  - type: web
    name: stock-data-bot
    runtime: python
    repo: https://github.com/Ahashanahmed2/create_csv_bot
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: PORT
        value: 10000